version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node:13
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "this is the build job"
      - run:
          -name: "Install Dependencies"
          -command: |
            npm install --save
      - run:
          -name: "registry"
          -command: |
          docker tag simple-node onosgb/simple-node
      - run:
          -name: "docker push"
          -command: |
          docker build -t onosgb/simple-node .

  test:
    docker:
      - image: circleci/node:13
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
